spring:
  application:
    name: whybuychat
  profiles:
    active: local
  h2:
    console:
      enabled: true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always